[workspace]
members = [
  "spdk-core",
  "backends/blindbit-v1",
  "spdk-wallet",
  "silentpayments",
  "scanners/local",
]
resolver = "3"

[workspace.dependencies]
# Internal workspace crates
spdk-core = { path = "spdk-core" }
spdk-wallet = { path = "spdk-wallet" }
silentpayments = { path = "silentpayments" }
backend-blindbit-v1 = { path = "backends/blindbit-v1" }
local-scanner = { path = "scanners/local" }

# Core dependencies - shared across crates
anyhow = "1.0"
bech32 = "0.9"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
bip321 = { git = "https://gitlab.com/Sosthene00/bark.git", rev = "83ab79264159869503b16fa475e0ed61ffa33174", default-features = false }
bitcoin = { version = "0.32.8", features = ["serde", "rand", "base64"] }
bitcoin_hashes = "0.14"
rayon = "1.10.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = "0.3"
async-trait = "0.1"
log = "0.4"
hex = { version = "0.4.3", features = ["serde"] }
bdk_coin_select = "0.4.0"
reqwest = { version = "0.12.4", features = [
  "json",
  "rustls-tls",
  "gzip",
], default-features = false }
rust-dleq = { git = "https://github.com/Sosthene00/rust-dleq.git", rev = "097644a14d87c454e9bd9895de2e60992ff1ba93", default-features = false }
secp256k1 = { version = "0.29.0" }

[workspace.package]
edition = "2024"
repository = "https://github.com/cygnet3/spdk"
authors = ["cygnet <cygnet3@proton.me>"]
license = "MIT"

[workspace.lints.clippy]
pedantic = "warn"
# Enable selected 'nursery' and 'restriction' lints...
allow_attributes = "warn"
branches_sharing_code = "warn"
iter_on_empty_collections = "warn"
iter_on_single_items = "warn"
missing_const_for_fn = "warn"
renamed_function_params = "warn"
str_to_string = "warn"
try_err = "warn"
unused_trait_names = "warn"
use_self = "warn"
# Probably counterproductive to document errors of all publicly visible fns before the code has matured:
missing_errors_doc = { level = "allow", priority = 1 }
# Panics shall generally only result from bugs in callee code, so this gives too many false positives:
missing_panics_doc = { level = "allow", priority = 1 }
# Probably shouldn't annotate every (public) pure fn with '#[must_use]', so too many false positives:
must_use_candidate = { level = "allow", priority = 1 }
